### ISSUE TITLE
the solved command does not respond when ctfnote is down

### ISSUE THREAD

**Issue by lucidBrot** [0rganizers/the-organizer#10]
temporary workaround(?) is to `/ctfnote_update_auth disabled a b` but there should be better exception handling for errors or timeouts in the ctfnote part so that the rest still works correctly.

In addition, there should also be a 
```python
if not enabled:
  return
```

in the `update_flag` method in `ctfnote.py`: https://github.com/0rganizers/the-organizer/blob/master/organizers_bot/ctfnote.py#L564

**Comment by RobinJadoul** [comment]
Somewhat fixed in 000f3c91 so closing it in favor of #15
